# Generated by Django 6.0.3 on 2026-03-19 12:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Plan Básico'), ('pro', 'Plan Pro')], default='free', max_length=10)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre Empresa')),
                ('rut', models.CharField(max_length=12, validators=[users.models.validate_rut], verbose_name='RUT')),
                ('rubro', models.CharField(choices=[('gasfiteria', 'Gasfitería'), ('electricidad', 'Electricidad'), ('construccion', 'Construcción General'), ('carpinteria', 'Carpintería'), ('pintura', 'Pintura'), ('ceramica', 'Cerámica y Pisos'), ('climatizacion', 'Climatización / HVAC'), ('techumbres', 'Techumbres'), ('otro', 'Otro')], default='construccion', max_length=50, verbose_name='Rubro')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('city', models.CharField(default='Santiago', max_length=100, verbose_name='Ciudad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('brand_color', models.CharField(default='#1e40af', max_length=7, verbose_name='Color Principal')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('budget_validity_days', models.PositiveIntegerField(default=15, verbose_name='Validez (días)')),
                ('payment_terms', models.TextField(default='50% al inicio, 50% al finalizar la obra.', verbose_name='Condiciones de Pago')),
                ('notes_template', models.TextField(blank=True, verbose_name='Notas por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Contratista',
            },
        ),
    ]
