# Generated by Django 5.2.12 on 2026-04-15 17:05

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[users.validators.validate_image_upload], verbose_name='Logo'),
        ),
    ]
