# Generated by Django 5.2.12 on 2026-04-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contractorprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=100, verbose_name='ID preapproval MP')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('cancelled', 'Cancelado'), ('past_due', 'Vencido')], default='pending', max_length=20, verbose_name='Estado')),
                ('amount_clp', models.PositiveIntegerField(default=0, verbose_name='Monto CLP')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima cobranza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=100, verbose_name='ID pago MP')),
                ('amount', models.PositiveIntegerField(verbose_name='Monto CLP')),
                ('paid_at', models.DateTimeField(verbose_name='Fecha de pago')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.subscription')),
            ],
            options={
                'verbose_name': 'Pago',
                'ordering': ['-paid_at'],
            },
        ),
    ]
