# Generated by Django 5.2.12 on 2026-04-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budgets", "0006_budgetpublictoken_expires_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("folio", models.PositiveIntegerField(verbose_name="Folio")),
                ("tipo_dte", models.PositiveSmallIntegerField(choices=[(33, "Factura Electrónica"), (39, "Boleta Electrónica")], default=39, verbose_name="Tipo DTE")),
                ("sii_track_id", models.CharField(blank=True, max_length=100, verbose_name="Track ID SII")),
                ("xml_url", models.URLField(blank=True, verbose_name="URL XML")),
                ("pdf_url", models.URLField(blank=True, verbose_name="URL PDF")),
                ("status", models.CharField(choices=[("pending", "Pendiente"), ("accepted", "Aceptada"), ("rejected", "Rechazada")], default="pending", max_length=20, verbose_name="Estado")),
                ("issued_at", models.DateTimeField(auto_now_add=True, verbose_name="Emitida el")),
                ("total_clp", models.PositiveIntegerField(verbose_name="Total CLP")),
                ("budget", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoice", to="budgets.budget")),
                ("contractor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Factura/Boleta",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, verbose_name="Descripción")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Cantidad")),
                ("unit_price", models.PositiveIntegerField(verbose_name="Precio Unitario CLP")),
                ("subtotal", models.PositiveIntegerField(verbose_name="Subtotal CLP")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="billing.invoice")),
            ],
            options={
                "verbose_name": "Línea de Factura",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["contractor", "status"], name="billing_inv_contrac_aef09a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("contractor", "tipo_dte", "folio")},
        ),
    ]
