# Generated by Django 5.2.12 on 2026-04-15 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['contractor', 'name'], name='clients_cli_contrac_d873a5_idx'),
        ),
    ]
