# Generated by Django 6.0.3 on 2026-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('materiales', 'Materiales'), ('herramientas', 'Herramientas'), ('electricidad', 'Eléctrico'), ('gasfiteria', 'Gasfitería'), ('ceramica', 'Cerámica'), ('pintura', 'Pintura'), ('madera', 'Madera'), ('otro', 'Otro')], default='materiales', max_length=50, verbose_name='Categoría')),
                ('unit', models.CharField(choices=[('un', 'Unidad'), ('m2', 'm²'), ('m3', 'm³'), ('ml', 'Metro lineal'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('hr', 'Hora'), ('gl', 'Global'), ('bls', 'Bolsa'), ('pk', 'Pack')], default='un', max_length=10, verbose_name='Unidad')),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio Costo')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio Venta')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU/Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['name'],
            },
        ),
    ]
