# Generated by Django 5.2.12 on 2026-04-15 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['contractor', 'is_active'], name='catalog_pro_contrac_310bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['contractor', 'category'], name='catalog_pro_contrac_cd73c4_idx'),
        ),
    ]
