# Generated by Django 6.0.3 on 2026-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='N° Presupuesto')),
                ('title', models.CharField(max_length=300, verbose_name='Título / Obra')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado al Cliente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='borrador', max_length=20, verbose_name='Estado')),
                ('validity_days', models.PositiveIntegerField(default=15, verbose_name='Validez (días)')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Condiciones de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IVA %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Descripción del Trabajo')),
                ('unit', models.CharField(choices=[('un', 'Unidad'), ('m2', 'm²'), ('m3', 'm³'), ('ml', 'Metro lineal'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('hr', 'Hora'), ('gl', 'Global'), ('bls', 'Bolsa'), ('pk', 'Pack')], default='gl', max_length=10, verbose_name='Unidad')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad / Horas')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Unitario')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Descripción')),
                ('unit', models.CharField(choices=[('un', 'Unidad'), ('m2', 'm²'), ('m3', 'm³'), ('ml', 'Metro lineal'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('hr', 'Hora'), ('gl', 'Global'), ('bls', 'Bolsa'), ('pk', 'Pack')], default='un', max_length=10, verbose_name='Unidad')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Unitario')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
