# Generated by Django 5.2.13 on 2026-05-02 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0007_budgetattachment_budgetsignature_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("rubro", models.CharField(max_length=50, verbose_name="Categoría")),
                ("icon", models.CharField(default="📦", max_length=10, verbose_name="Ícono")),
                ("input_label", models.CharField(default="Superficie", max_length=100, verbose_name="Etiqueta de medida")),
                ("input_unit", models.CharField(default="m²", max_length=20, verbose_name="Unidad de medida")),
                ("input_placeholder", models.CharField(blank=True, max_length=100, verbose_name="Placeholder")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contractor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Receta de materiales",
                "verbose_name_plural": "Recetas de materiales",
                "ordering": ["rubro", "name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRecipeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Material")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("un", "Unidad"),
                            ("m2", "m²"),
                            ("m3", "m³"),
                            ("ml", "Metro lineal"),
                            ("kg", "Kilogramo"),
                            ("lt", "Litro"),
                            ("hr", "Hora"),
                            ("gl", "Global"),
                            ("bls", "Bolsa"),
                            ("pk", "Pack"),
                        ],
                        default="un",
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
                ("quantity_factor", models.DecimalField(decimal_places=4, max_digits=8, verbose_name="Factor por unidad")),
                ("order", models.PositiveIntegerField(default=0)),
                ("recipe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="budgets.materialrecipe")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
